version: '3'
services:
    vsc-server:
        build: vsc
        container_name: code-server-tasmotabatmanager
        hostname: code-server-kostal-idm
        networks:
            tasmotabatmanager-net:
        volumes:
            - $HOME/.config:/home/coder/.config
            - $PWD:/home/coder/project
        environment:
            - DOCKER_USER=$USER
        user: "${EXAMPLE_UID}:${EXAMPLE_GID}"
        expose:
            - 8080
        ports:
            - 8080:8080

networks:
    tasmotabatmanager-net:

